/// Flutter icons Schedule
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Schedule
///      fonts:
///       - asset: fonts/Schedule.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Schedule {
  Schedule._();

  static const _kFontFam = 'Schedule';
  static const String? _kFontPkg = null;

  static const IconData threedee_rotation = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifyingglass = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
