/// Flutter icons Schedule
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Schedule
///      fonts:
///       - asset: fonts/Schedule.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Schedule {
  Schedule._();

  static const _kFontFam = 'Schedule';
  static const String? _kFontPkg = null;

  static const IconData book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifyingglass = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noti = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
